# Generated by Django 5.2.8 on 2025-11-23 22:45

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.PositiveIntegerField(default=502)),
                ('protocol', models.PositiveIntegerField(choices=[(0, 'Modbus TCP'), (1, 'Modbus UDP'), (2, 'Modbus Serial')], default=0)),
                ('word_order', models.TextField(choices=[('big', 'Big Endian'), ('little', 'Little Endian')], default='big')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(default=1)),
                ('alias', models.CharField(max_length=100)),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('channel', models.PositiveIntegerField(choices=[(0, 'Coil'), (1, 'Discrete Input'), (2, 'Holding Register'), (3, 'Input Register')])),
                ('data_type', models.PositiveIntegerField(choices=[(0, 'Boolean'), (1, 'Signed Int16'), (2, 'Unsigned Int16'), (3, 'Signed Int32'), (4, 'Unsigned Int32'), (5, 'Signed Int64'), (6, 'Unsigned Int64'), (7, 'Float32'), (8, 'Float64'), (9, 'String')])),
                ('address', models.PositiveIntegerField(default=0)),
                ('read_amount', models.PositiveIntegerField(default=1)),
                ('max_history_entries', models.PositiveIntegerField(default=0, help_text='Keep at most N recent entries; -1 = unlimited')),
                ('last_updated', models.DateTimeField(null=True)),
                ('current_value', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='plc_tools.device')),
            ],
            options={
                'unique_together': {('device', 'channel', 'address', 'unit_id')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.TextField(choices=[('led', 'LED Indicator'), ('bool_label', 'Boolean Label'), ('val', 'Numeric Value'), ('chart', 'Time-Series Chart'), ('button', 'Button'), ('label', 'Text Label'), ('switch', 'Switch'), ('meter', 'Meter'), ('slider', 'Slider')])),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='plc_tools.dashboard')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='plc_tools.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_value', models.JSONField(help_text='Value that triggers this alarm')),
                ('message', models.CharField(help_text="e.g., 'Sump Pump Failure - Check Breaker'", max_length=200)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('crit', 'Critical')])),
                ('notification_cooldown', models.DurationField(default=datetime.timedelta(seconds=60), help_text="Don't resend email for this long")),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_configs', to='plc_tools.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagWriteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_tools.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ActivatedAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_tools.alarmconfig')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['config', '-timestamp'], name='plc_tools_a_config__2e1ff1_idx')],
                'unique_together': {('config', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AlarmSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('alarm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_tools.alarmconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alarm_config')},
            },
        ),
        migrations.CreateModel(
            name='TagHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.JSONField(null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='plc_tools.tag')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tag', '-timestamp'], name='plc_tools_t_tag_id_1f5341_idx')],
            },
        ),
    ]
