# Generated by Django 6.0 on 2025-12-30 00:57

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.PositiveIntegerField(default=502)),
                ('protocol', models.TextField(choices=[('tcp', 'Modbus TCP'), ('udp', 'Modbus UDP'), ('rtu', 'Modbus Serial')], default='tcp')),
                ('word_order', models.TextField(choices=[('big', 'Big Endian'), ('little', 'Little Endian')], default='big')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='dashboard_previews/')),
                ('column_count', models.PositiveSmallIntegerField(default=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(default=1)),
                ('alias', models.CharField(max_length=100)),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('channel', models.TextField(choices=[('coil', 'Coil'), ('di', 'Discrete Input'), ('hr', 'Holding Register'), ('ir', 'Input Register')])),
                ('data_type', models.TextField(choices=[('bool', 'Boolean'), ('int16', 'Signed Int16'), ('uint16', 'Unsigned Int16'), ('int32', 'Signed Int32'), ('uint32', 'Unsigned Int32'), ('int64', 'Signed Int64'), ('uint64', 'Unsigned Int64'), ('float32', 'Float32'), ('float64', 'Float64'), ('string', 'String')])),
                ('address', models.PositiveIntegerField(default=0)),
                ('bit_index', models.PositiveSmallIntegerField(default=0)),
                ('read_amount', models.PositiveIntegerField(default=1)),
                ('last_history_at', models.DateTimeField(blank=True, null=True)),
                ('history_interval', models.DurationField(default=datetime.timedelta(seconds=1))),
                ('history_retention', models.DurationField(default=datetime.timedelta(0))),
                ('last_updated', models.DateTimeField(null=True)),
                ('current_value', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.device')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('device', 'channel', 'address', 'unit_id', 'bit_index')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.TextField(choices=[('led', 'LED Indicator'), ('bool_label', 'Boolean Label'), ('multi_label', 'Multi-Value Label'), ('number_label', 'Number Label'), ('number_input', 'Number Input'), ('chart', 'Time-Series Chart'), ('button', 'Button'), ('label', 'Text Label'), ('switch', 'Switch'), ('meter', 'Meter'), ('slider', 'Slider'), ('dropdown', 'Dropdown'), ('gauge', 'Radial Gauge')])),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='main.dashboard')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('trigger_value', models.JSONField(help_text='Value that triggers this alarm')),
                ('operator', models.TextField(choices=[('equals', 'Equals'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than')], default='equals')),
                ('enabled', models.BooleanField(default=True)),
                ('alias', models.CharField(max_length=100)),
                ('message', models.CharField(default='', help_text="e.g., 'Sump Pump Failure - Check Breaker'", max_length=200)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('crit', 'Critical')])),
                ('notification_cooldown', models.DurationField(default=datetime.timedelta(seconds=60), help_text="Don't resend email for this long")),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_configs', to='main.tag')),
            ],
            options={
                'unique_together': {('alias', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='TagWriteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ActivatedAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alarmconfig')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['config', '-timestamp'], name='main_activa_config__0dfcc2_idx')],
                'unique_together': {('config', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AlarmSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('alarm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alarmconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alarm_config')},
            },
        ),
        migrations.CreateModel(
            name='TagHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.JSONField(null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.tag')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tag', '-timestamp'], name='main_taghis_tag_id_b23b73_idx')],
            },
        ),
    ]
